### ISSUE TITLE
how missing steps?

### ISSUE THREAD

**Issue by johnfelipe** [Data-Science-Community-SRM/Hand-Gesture-Recognition-Rock-Paper-Scissor#7]
apt install python3-pip
    pip install streamlit
    
    git clone https://github.com/Data-Science-Community-SRM/Hand-Gesture-Recognition-Rock-Paper-Scissor.git
    
    cd Hand-Gesture-Recognition-Rock-Paper-Scissor/
    pip install -r requirements.txt

and next

    streamlit run app.py

and show me this

![SNAG-0608](https://user-images.githubusercontent.com/428820/120914460-f4706280-c663-11eb-81ea-b215cb47b91c.png)

wich step i missing?

**Comment by stagnito** [comment]
The Model_4_classes.h5 file is not present in this repository, You need to run the python notebook containing the model, which would generate the Model_4_classes.h5 file (Saved Weights File) after generating the file,  Keep both,  `Model_4_classes.h5` and `app.py` files in the same directory. Then run the command `streamlit run app.py`

**Comment by johnfelipe** [comment]
Can u tell me instructions for run python in local or better do it in Google colab?

**Comment by stagnito** [comment]
Yes, If u have have all requirements installed then you can run the python notebook on your local system, else Google Colab would be better.

**Comment by johnfelipe** [comment]
can u show me how do it in colab, pls

**Comment by johnfelipe** [comment]
dear can u help me with instructions for run notebook in colab....

**Comment by stagnito** [comment]
The IPython Notebok file is present here `Hand-Gesture-Recognition-Rock-Paper-Scissor/Inception-Model/TrainInception_4classes.ipynb` , Download the notebook, and upload the notebook file in your google drive, then open google colab there open your notebook file and run all cells, once done a file named `Dataset-final4th-Inception(150x150 rps).h5`  will be created. Copy that file into the directory where the `app.py` is located. 
Then make a change in the app.py file line 6:
Replace,
`model = tf.keras.models.load_model('Model_4_classes.h5')`
With,
`model = tf.keras.models.load_model('Dataset-final4th-Inception(150x150 rps).h5')`
Next run `app.py`.

If you are still facing issues in running notebook on colab please check there are a lot of sources online. I am closing this issue, feel free to re-open the issue if the problem persists.

**Comment by johnfelipe** [comment]
![SNAG-0698](https://user-images.githubusercontent.com/428820/121784624-8d2e4300-cb7a-11eb-88b0-0aa0556a6f85.png)
im stock in that cell, pls tell me what need to do
tnks

**Comment by johnfelipe** [comment]
Can u help me to complete all blocks
